language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "liu101937" | docker login -u "mrdabing" --password-stdin
  - docker build -t mrdabing/pea3nut-info:latest .
  - docker push mrdabing/pea3nut-info:latest